telegram_token: ""
telegram_chat_id: -123

cameras:
  - name: "Camera 1"
    enabled: true
    snapshot_url: "http://192.168.0.1"
    cooldown: 5
    threshold_percent: 4.5
    min_threshold_percent: 4.0

  - name: "Camera 2"
    enabled: true
    snapshot_url: "http://192.168.0.2"
    cooldown: 5
    threshold_percent: 5.5
    min_threshold_percent: 4.0

  - name: "Camera 3"
    enabled: true
    snapshot_url: "http://192.168.0.3"
    cooldown: 5
    threshold_percent: 2.8
    min_threshold_percent: 4.0
